TeamProject-Forum-ASP-NET/Controllers/User/HomeController.cs
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TeamProject_Forum_ASP_NET.Entities;
using TeamProject_Forum_ASP_NET.ViewModels;

namespace TeamProject_Forum_ASP_NET.Controllers
{

    public class HomeController : Controller
    {
        public ActionResult Index(int? page)
        {
            using (var db = new ForumDBContext())
            {
                var questions = db.Questions
                    .Include(q => q.Answers)
                    .Include(q => q.Tags)
                    .Include(q => q.Author)
                    .OrderBy(q => q.DateAdded)
                    .ToList();

                return View(questions.ToPagedList(page ?? 1, 3));
            }
        }

        public ActionResult ListCategories(int? categoryId)
        {
            using (var db = new ForumDBContext())
            {
                var categories = db.Categories
                    .OrderBy(c => c.Name)
                    .ToList();

                ViewBag.categoryId = categoryId;

                return PartialView("ListCategories", categories);
            }
        }

        [HttpGet]
        public ActionResult ListQuestionsByCategory(int? categoryId, int? page)
        {
            if (categoryId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var db = new ForumDBContext())
            {
                var questions = db.Questions
                    .Where(q => q.CategoryId == categoryId)
                    .Include(q => q.Answers)
                    .Include(q => q.Tags)
                    .Include(q => q.Author)
                    .OrderBy(q => q.DateAdded)
                    .ToList()
                    .ToPagedList(page ?? 1, 3);

                if (questions == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                ViewBag.categoryId = categoryId;

                return View(questions);
            }
        }

        //public ActionResult About()
        //{
        //    ViewBag.Message = "Your application description page.";

        //    return View();
        //}

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpGet]
        public ActionResult RankList(int? page)
        {
            using (var db = new ForumDBContext())
            {
                var users = db.Users
                    .OrderByDescending(u => u.PostsCount)
                    .ThenBy(u => u.UserName)
                    .ToList();

                //foreach (var user in users)
                //{
                //    var photoPath = Url.Content("~/Content/Images/ProfilePhotos/" + user.UserName + ".png") + "?time=" + DateTime.Now.ToString();
                //    string fullPhotoPathUser = Request.MapPath("~/Content/Images/ProfilePhotos/" + user.UserName + ".png");

                //    var defaultPhotoPath = Url.Content("~/Content/Images/ProfilePhotos/NoPhoto.png");
                //    user.ProfilePhotoPath = System.IO.File.Exists(fullPhotoPathUser) ? photoPath : defaultPhotoPath;

                //}

                return View(users.ToPagedList(page ?? 1, 3));
            }
        }
    }
}

TeamProject-Forum-ASP-NET/Controllers/User/TagController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TeamProject_Forum_ASP_NET.Entities;
using PagedList;
using PagedList.Mvc;

namespace TeamProject_Forum_ASP_NET.Controllers.User
{
    public class TagController : Controller
    {
        // GET: Tag
        public ActionResult ListQuestionsByTag(int? id, int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            using (var db = new ForumDBContext())
            {
                var questions = db.Tags
                    .Include(t => t.Questions.Select(q => q.Tags))
                    .Include(t => t.Questions.Select(q => q.Author))
                    .Include(t => t.Questions.Select(q => q.Answers))
                    .FirstOrDefault(t => t.Id == id)
                    .Questions
                    .OrderBy(q => q.DateAdded)
                    .ToList();

                return View(questions.ToPagedList(page ?? 1, 3));
            }
        }
    }
}

TeamProject-Forum-ASP-NET/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TeamProject-Forum-ASP-NET/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Us";
}
<h2>@ViewBag.Title</h2>


<address>
    Street Liliache<br />
    Sofia, BG 1000<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<iframe width="650"
        height="450"
        frameborder="0" style="border: 0"
        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAX4SVFXkwrvgFHK90XLVBekyBhoCh_jw8&q=Ovcha+Kupel,Sofia+Bulgaria" allowfullscreen>
</iframe>

<address>
    <strong>Support:</strong>   <a href="mailto:TeamPrometheus@mars.com">TeamPrometheus@mars.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:TeamPrometheus@mars.com">MarketDepartmentTeamPrometheus@mars.com</a>
</address>

TeamProject-Forum-ASP-NET/Views/Home/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<TeamProject_Forum_ASP_NET.Entities.Question>

@{
    ViewBag.Title = "Home Page";
}

<div class="container">
    <div class="row">
        <div class="col-md-2">
            @Html.Action("ListCategories", "Home")
        </div>
        <div class="col-md-8">
            @foreach (var question in Model)
            {
                <div class="row well">
                    <div class="col-md-2">
                        @{
                            @*var postImgUrl = Url.Content("~/Content/Images/ProfilePhotos/" + question.Author.UserName + ".png") + "?time=" + DateTime.Now.ToString();

                            string fullPathQuestion = Request.MapPath("~/Content/Images/ProfilePhotos/" + question.Author.UserName + ".png");
                            var defaultImgUrl = Url.Content("~/Content/Images/ProfilePhotos/NoPhoto.png");

                            if (System.IO.File.Exists(fullPathQuestion))
                            {
                                <img src="@postImgUrl" height="75" width="75" alt="Profile Photo" style="margin-top:30px" />
                            }
                            else
                            {
                                <img src="@defaultImgUrl" height="75" width="75" alt="Profile Photo" style="margin-top:30px" />
                            }*@
                            <img src="@question.Author.ProfilePhotoPath" height="75" width="75" alt="Profile Photo" style="margin-top:30px" />
                        }
                       
                        <h4>@question.Author.UserName</h4>
                        <div>Posts: @question.Author.PostsCount</div>
                    </div>
                    <div class="col-md-10">
                        <article>
                            <header>
                                <h2>
                                    @Html.ActionLink(question.Title, "ViewAnswers", "Question", new { @id = question.Id }, null)
                                </h2>
                            </header>
                            <footer>
                                <small>--posted on @question.DateAdded</small>
                                <small>-- @question.ViewCount Views</small>
                                <small>-- @question.Answers.Count Answers</small>
                                <div style="margin-top:15px;">
                                    @foreach (var tag in question.Tags)
                                    {
                                        <span>@Html.ActionLink(tag.Name, "ListQuestionsByTag", "Tag", new { id = tag.Id }, new { @class = "btn btn-default btn-xs" })</span>
                                    }
                                </div>
                            </footer>
                        </article>
                    </div>
                </div>
                            }
            @Html.PagedListPager(Model, page => Url.Action("Index", "Home", new { page }),
                    new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
        </div>
    </div>
</div>

TeamProject-Forum-ASP-NET/Views/Home/ListCategories.cshtml
@using PagedList;
@using PagedList.Mvc;

@model List<TeamProject_Forum_ASP_NET.Entities.Category>

@{
    ViewBag.Title = "ListCategories";
}


<ul class="nav nav-pills nav-stacked" style="margin-top:50px;">
    @foreach (var category in Model)
    {
        if (ViewBag.categoryId == category.Id)
        {
            @:<li class="active">
        }

        else
        {
            @:<li>
        }

        @Html.ActionLink(string.Format($"{category.Name}"), "ListQuestionsByCategory", "Home", new { categoryId = category.Id }, null)
    }
</ul>
   



TeamProject-Forum-ASP-NET/Views/Home/ListQuestionsByCategory.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<TeamProject_Forum_ASP_NET.Entities.Question>

@{
    ViewBag.Title = "ListQuestionsByCategory";
}

<div class="container">
    <div class="row">
        <div class="col-md-2">
            @Html.Action("ListCategories", "Home",new { categoryId = ViewBag.categoryId })
        </div>
        <div class="col-md-8">
            @foreach (var question in Model)
            {
                <div class="row well">
                    <div class="col-md-2">
                        
                        <img src="@question.Author.ProfilePhotoPath" height="75" width="75" alt="Profile Photo" style="margin-top:30px" />
                        <br />
                        <br />
                        <h4>@question.Author.UserName</h4>
                        <div>Posts: @question.Author.PostsCount</div>
                    </div>
                    <div class="col-md-10">
                        <article>
                            <header>
                                <h2>
                                    @Html.ActionLink(question.Title, "ViewAnswers", "Question", new { @id = question.Id }, null)
                                </h2>
                            </header>
                            <footer>
                                <small>--posted on @question.DateAdded</small>
                                <small>-- @question.ViewCount Views</small>
                                <small>-- @question.Answers.Count Answers</small>
                                <div style="margin-top:15px;">
                                    @foreach (var tag in question.Tags)
                                    {
                                        <span>@Html.ActionLink(tag.Name, "ListQuestionsByTag", "Tag", new { @id = tag.Id }, new { @class = "btn btn-default btn-xs" })</span>
                                    }
                                </div>
                            </footer>
                        </article>
                    </div>
                </div>
                            }
            @Html.PagedListPager(Model, page => Url.Action("ListQuestionsByCategory","Home", new { page , categoryId = Request.QueryString["categoryId"] }),
                    new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
        </div>
    </div>
</div>

TeamProject-Forum-ASP-NET/Views/Home/RankList.cshtml
@using PagedList
@using PagedList.Mvc

@model IPagedList<TeamProject_Forum_ASP_NET.Models.ApplicationUser>

@{
    ViewBag.Title = "RankList";
}

<div class="container">
    <div class="row">
        <div class="col-md-2">
            @Html.Action("ListCategories", "Home")
        </div>
        <div class="col-md-8">
            @foreach (var user in Model)
            {
                <div class="row well">
                    <div class="col-md-2">

                        <img src="@user.ProfilePhotoPath" height="75" width="75" alt="Profile Photo" style="margin-top:30px" />

                    </div>

                    <div class="col-md-10">
                        <header>
                            <h3>
                                @user.UserName
                            </h3>
                        </header>
                        <div>
                            <div>Full Name: @user.FullName</div>
                            <div>Email: @user.Email</div>
                            <div>Posts Count: @user.PostsCount</div>
                        </div>
                    </div>
                </div>
            }
            @Html.PagedListPager(Model, page => Url.Action("RankList", "Home", new { page }),
               new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
        </div>
    </div>
</div>