TeamProject-Forum-ASP-NET/Entities/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using TeamProject_Forum_ASP_NET.Models;

namespace TeamProject_Forum_ASP_NET.Entities
{
    public class Question
    {
        private ICollection<Tag> tags;
        private ICollection<Answer> answers;

        public Question()
        {
            this.DateAdded = DateTime.Now;
            this.answers = new HashSet<Answer>();
            this.tags = new HashSet<Tag>();
        }

        public Question(string authorId, string title, string content, int categoryId)
        {
            this.AuthorId = authorId;
            this.Title = title;
            this.Content = content;
            this.CategoryId = categoryId;
            this.DateAdded = DateTime.Now;
            this.answers = new HashSet<Answer>();
            this.tags = new HashSet<Tag>();
        }

        [Key]
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        public int ViewCount { get; set; }

        public DateTime DateAdded { get; set; }

        [ForeignKey("Author")]
        public string AuthorId { get; set; }

        public virtual ApplicationUser Author { get; set; }

        public virtual ICollection<Answer> Answers
        {
            get { return this.answers; }
            set { this.answers = value; }
        }

        [ForeignKey("Category")]
        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }

        public virtual ICollection<Tag> Tags
        {
            get { return this.tags; }
            set { this.tags = value; }
        }
    }
}

TeamProject-Forum-ASP-NET/ViewModels/QuestionViewModel.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TeamProject_Forum_ASP_NET.Entities;
using TeamProject_Forum_ASP_NET.Models;

namespace TeamProject_Forum_ASP_NET.ViewModels
{
    public class QuestionViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        public int ViewCount { get; set; }

        public string AuthorId { get; set; }

        public virtual ApplicationUser Author { get; set; }

        public virtual Answer Answer { get; set; }

        public IPagedList<Answer> Answers { get; set; }

        [Required]
        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }

        public ICollection<Category> Categories { get; set; }

        [Required]
        public string Tags { get; set; }

        public DateTime DateAdded { get; set; }

        public bool IsAuthor(string authorName, string postAuthor)
        {
            return authorName.Equals(postAuthor);
        }
    }
}

TeamProject-Forum-ASP-NET/Controllers/User/AnswerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TeamProject_Forum_ASP_NET.Entities;
using TeamProject_Forum_ASP_NET.ViewModels;

namespace TeamProject_Forum_ASP_NET.Controllers.User
{
    public class AnswerController : Controller
    {
        private ForumDBContext db = new ForumDBContext();

        [HttpGet]
        [Authorize]
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = new AnswerViewModel();
            var question = db.Questions.FirstOrDefault(q => q.Id == id);

            if (question == null)
            {
                return HttpNotFound();
            }

            model.QuestionId = question.Id;

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(AnswerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var author = db.Users
                   .First(u => u.UserName == this.User.Identity.Name);
                var authorId = author.Id;

                var answer = new Answer(authorId, model.Content, model.QuestionId);
                author.PostsCount++;

                db.Entry(author).State = EntityState.Modified;
                db.Answers.Add(answer);
                db.SaveChanges();

                return RedirectToAction("ViewAnswers", "Question", new { id = model.QuestionId });
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var answer = db.Answers.FirstOrDefault(q => q.Id == id);

            if (answer == null)
            {
                return HttpNotFound();
            }

            var model = new AnswerViewModel();
            model.Author = answer.Author;
            if (!IsUserAutorizedToEdit(model))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            model.Id = answer.Id;
            model.Content = answer.Content;
            model.QuestionId = answer.QuestionId;

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(AnswerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var answer = db.Answers.FirstOrDefault(a => a.Id == model.Id);

                answer.Content = model.Content;

                db.Entry(answer).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("ViewAnswers", "Question", new { id = model.QuestionId });
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
                        
            var answer = db.Answers.FirstOrDefault(q => q.Id == id);

            if (answer == null)
            {
                return HttpNotFound();
            }

            var model = new AnswerViewModel();
            model.Author = answer.Author;
            if (!IsUserAutorizedToEdit(model))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            model.Id = answer.Id;
            model.Content = answer.Content;
            model.QuestionId = answer.QuestionId;

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(AnswerViewModel model)
        {
            var answer = db.Answers.FirstOrDefault(a => a.Id == model.Id);
            var author = answer.Author;

            author.PostsCount--;
            db.Entry(author).State = EntityState.Modified;
            db.Answers.Remove(answer);
            db.SaveChanges();

            return RedirectToAction("ViewAnswers", "Question", new { id = model.QuestionId });
        }

        private bool IsUserAutorizedToEdit(AnswerViewModel answerViewModel)
        {
            bool isAdmin = this.User.IsInRole("Admin");
            bool isAuthor = answerViewModel.IsAuthor(this.User.Identity.Name);

            return isAdmin || isAuthor;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TeamProject-Forum-ASP-NET/Controllers/User/QuestionController.cs
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TeamProject_Forum_ASP_NET.Entities;
using TeamProject_Forum_ASP_NET.ViewModels;

namespace TeamProject_Forum_ASP_NET.Controllers.User
{
    public class QuestionController : Controller
    {
        private ForumDBContext db = new ForumDBContext();

        [HttpGet]
        public ActionResult ViewAnswers(int? id, int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = new QuestionViewModel();
            var question = db.Questions
                .Include(a => a.Author)
                .FirstOrDefault(q => q.Id == id);

            if (question == null)
            {
                return HttpNotFound();
            }

            var answers = db.Answers
                .Where(q => q.QuestionId == id)
                .Include(a => a.Author)
                .OrderBy(a => a.DateAdded)
                .ToList()
                .ToPagedList(page ?? 1, 3);

            question.ViewCount++;

            db.Entry(question).State = EntityState.Modified;
            db.SaveChanges();

            model.Id = question.Id;
            model.Title = question.Title;
            model.Content = question.Content;
            model.ViewCount = question.ViewCount;
            model.DateAdded = question.DateAdded;
            model.Author = question.Author;
            model.Answers = answers;
           
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            var model = new QuestionViewModel();
            model.Categories = db.Categories.OrderBy(c => c.Name).ToList();

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(QuestionViewModel model)
        {
            if (ModelState.IsValid)
            {
                var author = db.Users
                    .First(u => u.UserName == this.User.Identity.Name);
                var authorId = author.Id;

                var question = new Question(authorId, model.Title, model.Content, model.CategoryId);
                author.PostsCount++;

                this.SetQuestionTags(question, model, db);

                db.Entry(author).State = EntityState.Modified;
                db.Questions.Add(question);
                db.SaveChanges();

                return RedirectToAction("ViewAnswers", "Question", new { id = question.Id });
            }

            model.Categories = db.Categories.OrderBy(c => c.Name).ToList();
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var question = db.Questions.Include(a => a.Author).FirstOrDefault(q => q.Id == id);

            if (question == null)
            {
                return HttpNotFound();
            }

            var model = new QuestionViewModel();
            model.Author = question.Author;

            if (!IsUserAutorizedToEdit(model))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            model.Id = question.Id;
            model.Title = question.Title;
            model.Content = question.Content;
            model.CategoryId = question.CategoryId;
            model.Categories = db.Categories.OrderBy(c => c.Name).ToList();

            model.Tags = string.Join(", ", question.Tags.Select(t => t.Name));

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(QuestionViewModel model)
        {
            if (ModelState.IsValid)
            {
                var question = db.Questions
                        .FirstOrDefault(q => q.Id == model.Id);

                question.Title = model.Title;
                question.Content = model.Content;
                question.CategoryId = model.CategoryId;
                this.SetQuestionTags(question, model, db);

                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("ViewAnswers", "Question", new { id = question.Id });
            }

            model.Categories = db.Categories.OrderBy(c => c.Name).ToList();
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var question = db.Questions
                .Where(q => q.Id == id)
                .Include(q => q.Author)
                .Include(q => q.Category)
                .FirstOrDefault();

            if (question == null)
            {
                return HttpNotFound();
            }

            ViewBag.TagsString = string.Join(", ", question.Tags.Select(t => t.Name));

            var model = new QuestionViewModel();
            model.Author = question.Author;

            if (!IsUserAutorizedToEdit(model))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            model.Id = question.Id;
            model.Title = question.Title;
            model.Content = question.Content;
            model.CategoryId = question.CategoryId;
            model.Category = question.Category;

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var question = db.Questions
                    .FirstOrDefault(q => q.Id == id);

            if (question == null)
            {
                return HttpNotFound();
            }

            var questionAuthor = question.Author;
            var answers = question.Answers.ToList();

            foreach (var answer in answers)
            {
                answer.Author.PostsCount--;
                db.Answers.Remove(answer);
            }

            questionAuthor.PostsCount--;
            db.Entry(questionAuthor).State = EntityState.Modified;
            db.Questions.Remove(question);
            db.SaveChanges();

            return RedirectToAction("ListQuestionsByCategory", "Home", new { categoryId = question.CategoryId });
        }

        private bool IsUserAutorizedToEdit(QuestionViewModel questionViewModel)
        {
            bool isAdmin = this.User.IsInRole("Admin");
            bool isAuthor = questionViewModel.IsAuthor(this.User.Identity.Name, questionViewModel.Author.UserName);

            return isAdmin || isAuthor;
        }

        private void SetQuestionTags(Question question, QuestionViewModel model, ForumDBContext db)
        {
            var tagsString = model.Tags.Split(new char[] { ',', ' ' }, StringSplitOptions.RemoveEmptyEntries).Select(t => t.ToLower()).Distinct();
            question.Tags.Clear();

            foreach (var tagString in tagsString)
            {
                Tag tag = db.Tags.FirstOrDefault(t => t.Name.Equals(tagString));

                if (tag == null)
                {
                    tag = new Tag() { Name = tagString };
                    db.Tags.Add(tag);
                }

                question.Tags.Add(tag);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TeamProject-Forum-ASP-NET/Views/Question/Create.cshtml
@model TeamProject_Forum_ASP_NET.ViewModels.QuestionViewModel

@{
    ViewBag.Title = "Create";
}

<div class="container">
    <div class="well">
        <h2>Create New Question</h2>
        @using (Html.BeginForm("Create", "Question", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.CategoryId, new { @class = "col-sm-4 control-label" })
                <div class="dropdown col-sm-4">
                    @Html.DropDownListFor(m => m.CategoryId,
                        new SelectList(Model.Categories, "Id", "Name"),
                        new { @class = "form-control col-sm-12" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Tags, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Tags, new { @class = "form-control col-sm-4" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-4">
                    @Html.ActionLink("Cancel", "Index", "Home", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        }
    </div>
</div>




TeamProject-Forum-ASP-NET/Views/Question/Delete.cshtml
@model TeamProject_Forum_ASP_NET.ViewModels.QuestionViewModel

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <div class="well">
        <h2>Delete Question</h2>
        @using (Html.BeginForm("Delete", "Question", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @readonly = "readonly", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Category, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Category.Name, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Tags, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBox("tagsString", (object)ViewBag.TagsString, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "ViewAnswers", "Question", new { @id = Model.Id }, new { @class = "btn btn-default" })
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>
        }
    </div>
</div>



TeamProject-Forum-ASP-NET/Views/Question/Edit.cshtml
@model TeamProject_Forum_ASP_NET.ViewModels.QuestionViewModel

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <div class="well">
        <h2>Edit Question</h2>
        @using (Html.BeginForm("Edit", "Question", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })

            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.AuthorId)

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.CategoryId, new { @class = "control-label col-sm-4" })
                <div class="dropdown col-sm-4">
                    @Html.DropDownListFor(m => m.CategoryId,
                        new SelectList(Model.Categories, "Id", "Name", Model.CategoryId),
                        new { @class = "form-control col-sm-12" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Tags, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Tags, new { @class = "form-control col-sm-4" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "ViewAnswers", "Question", new { @id = Model.Id }, new { @class = "btn btn-default" })
                    <input type="submit" value="Edit" class="btn btn-warning" />
                </div>
            </div>
        }
    </div>
</div>


TeamProject-Forum-ASP-NET/Views/Question/List.cshtml
@model List<TeamProject_Forum_ASP_NET.Entities.Question>

@{
    ViewBag.Title = "List";
}

<div class="container">
    <div class="row">
        @foreach (var question in Model)
        {
            <div class="col-sm-offset-2 col-sm-8">
                <article>
                    <header>
                        <h2>
                            @Html.ActionLink(@question.Title, "ViewAnswers", "Question", new { @id = question.Id }, null)
                        </h2>
                    </header>                    
                    <footer>
                        <small>
                            --author @question.Author.UserName
                        </small>
                        <small>--posted on @question.DateAdded</small>  
                        <small>-- @question.ViewCount Views</small>
                        <small>-- @question.Answers.Count Answers</small>                     
                    </footer>
                </article>
            </div>
        }
    </div>
</div>

TeamProject-Forum-ASP-NET/Views/Question/ViewAnswers.cshtml
@using PagedList;
@using PagedList.Mvc;

@using Microsoft.AspNet.Identity
@model TeamProject_Forum_ASP_NET.ViewModels.QuestionViewModel

@{
    ViewBag.Title = "ViewAnswers";
}

<div class="container">
    <div class="row">

        <div class="col-md-2">
            @Html.Action("ListCategories", "Home")
        </div>

        <div class="col-md-8">

            <div class="row well">
                <div class="col-md-2">

                    <img src="@Model.Author.ProfilePhotoPath" height="75" width="75" alt="Profile Photo" style="margin-top:30px" />


                    <h4>@Model.Author.UserName</h4>
                    <div>Posts: @Model.Author.PostsCount</div>
                </div>
                <div class="col-md-10">
                    <article>
                        <header>
                            <h2>
                                @Html.ActionLink(Model.Title, "ViewAnswers", "Question", new { @id = Model.Id }, null)
                            </h2>
                        </header>
                        <p>
                            @Model.Content
                        </p>
                        <footer>
                            <small>--posted on @Model.DateAdded</small>
                            <span class="pull-right">
                                @if (User.IsInRole("Admin") || Model.IsAuthor(User.Identity.Name, Model.Author.UserName))
                                {
                                    <span>@Html.ActionLink("Edit", "Edit", "Question", new { @id = Model.Id }, new { @class = "btn btn-warning btn-xs" })</span>
                                    <span>@Html.ActionLink("Delete", "Delete", "Question", new { @id = Model.Id }, new { @class = "btn btn-danger btn-xs" })</span>
                                }

                                <span>@Html.ActionLink("New Answer", "Create", "Answer", new { @id = Model.Id }, new { @class = "btn btn-primary btn-xs" })</span>
                            </span>
                        </footer>
                    </article>

                </div>
            </div>
            @Html.PagedListPager(Model.Answers, page => Url.Action("ViewAnswers", "Question", new { page }),
               new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })

            @foreach (var answer in Model.Answers)
            {
                <div class="row well">
                    <div class="col-md-2">

                        <img src="@answer.Author.ProfilePhotoPath" height="75" width="75" alt="Profile Photo" style="margin-top:30px" />
      
                        <h4>@answer.Author.UserName</h4>
                        <div>Posts: @answer.Author.PostsCount</div>
                    </div>

                    <div class="col-md-10">
                        <article>
                            <p style="margin-top:30px">
                                @answer.Content
                            </p>
                            <footer>
                                <small>--posted on @answer.DateAdded</small>
                                <span class="pull-right">
                                    @if (User.IsInRole("Admin") || Model.IsAuthor(User.Identity.Name, answer.Author.UserName))
                                    {
                                        <span>@Html.ActionLink("Edit", "Edit", "Answer", new { @id = answer.Id }, new { @class = "btn btn-warning btn-xs" })</span>
                                        <span>@Html.ActionLink("Delete", "Delete", "Answer", new { @id = answer.Id }, new { @class = "btn btn-danger btn-xs" })</span>
                                    }
                                </span>
                            </footer>
                        </article>
                    </div>
                </div>
            }

            @Html.PagedListPager(Model.Answers, page => Url.Action("ViewAnswers", "Question", new { page }),
               new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })

        </div>
    </div>
</div>